config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users

  get 'order', to: 'items#order', as: 'order_item'

  devise_scope :user do
    authenticated :user do
      root 'items#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  root 'items#index'

    resources :items

end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id           :integer          not null, primary key
#  code         :string
#  title        :string
#  description  :text
#  quantity     :integer
#  safetystock  :integer
#  reorderlevel :integer
#  leadtime     :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Item < ActiveRecord::Base
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password) }
        devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :logged_in_user, only: [:index, :new, :edit, :show]

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to action: "index"
    else
      render 'new'
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update!(item_params)
    redirect_to @item
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to action: "index"
  end

  def order
    @items = Item.all
  end

  private
    def item_params
      params.require(:item).permit(:code, :title, :description, :quantity, :safetystock, :reorderlevel, :leadtime)
    end

    def logged_in_user
      unless user_signed_in?
        flash[:danger] = "Please log in"
        redirect_to root_path
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/items/edit.html.erb
<div id="item-edit">
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3 content">
          <h2 class="title">New item</h2>
          <%= simple_form_for @item do |f| %>
            <%= f.input :title %>
            <%= f.input :code %>
            <%= f.input :description %>
            <%= f.input :quantity %>
            <%= f.input :safetystock %>
            <%= f.input :reorderlevel %>
            <%= f.input :leadtime %>
            <%= f.button :submit, class: "btn btn-default submit" %>
          <% end %>

          <%= link_to content_tag(:span, "", class: "glyphicon glyphicon-arrow-left") + "Back", item_path(@item) %>
      </div>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<div id="item-index">
  <h3>Inventory</h3>

  <div class="btn-group" role="group" aria-label="...">
    <%= link_to content_tag(:span, "", class: "glyphicon glyphicon-download-alt") + "New Item", new_item_path, class: "btn btn-default" %>
    <%= link_to content_tag(:span, "", class: "glyphicon glyphicon-earphone") + "Order List", order_item_path, class: "btn btn-default" %>
  </div>
  <br><br>

   <div class="panel panel-default">
    <div class="panel-body">
      <table class="table table-striped">
          <thead>
            <tr>
              <th>Code</th>
              <th>Title</th>
              <th class="center">Quantity</th>
              <th class="center">Reorder Level</th>
              <th class="center">Safety Stock</th>
            </tr>
          </thead>

          <tbody>
            <% @items.each do |item| %>
              <tr>
                <td><%= item.code %></td>
                <td><%= link_to item.title, item_path(item)  %></td>
                <td class="center"><%= item.quantity %></td>
                <td class="center"><%= item.reorderlevel %></td>
                <td class="center"><%= item.safetystock %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
</div>

app/views/items/new.html.erb
<div id="item-new">
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3 content">
          <h2 class="title">New item</h2>
          <%= simple_form_for @item do |f| %>
            <%= f.input :title %>
            <%= f.input :code %>
            <%= f.input :description %>
            <%= f.input :quantity %>
            <%= f.input :safetystock %>
            <%= f.input :reorderlevel %>
            <%= f.input :leadtime %>
            <%= f.button :submit, class: "btn btn-default submit" %>
          <% end %>

          <%= link_to content_tag(:span, "", class: "glyphicon glyphicon-arrow-left") + "Back", root_path %>
      </div>
    </div>
  </div>
</div>

app/views/items/order.html.erb
<div id="item-order">
  <h3>Order list</h3>

  <br><br>

  <div class="panel panel-default">
    <div class="panel-body">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Code</th>
            <th>Title</th>
            <th class="center">Quantity</th>
            <th class="center">Reorder level</th>
            <th class="center">Safety Stock</th>
          </tr>
        </thead>

        <tbody>
          <% @items.each do |item| %>
            <% if ((item.quantity < item.reorderlevel) || (item.quantity < item.safetystock)) %>
              <tr>
                <td><%= item.code %></td>
                <td><%= link_to item.title, item_path(item)  %></td>
                <td class="center"><%= item.quantity %></td>
                <td class="center"><%= item.reorderlevel %></td>
                <td class="center"><%= item.safetystock %></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
      <%= link_to content_tag(:span, "", class: "glyphicon glyphicon-arrow-left") + "Inventory", root_path %>
    </div>
  </div>
</div>

app/views/items/show.html.erb
<div id="item-show">
    <div class="container">
      <div class="row">
        <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3 content">
          <h2 class="title">Item</h2>
          <table class="table">
            <tbody>
              <tr>
                <td>Title</td>
                <td><%= @item.title %></td>
              </tr>
              <tr>
                <td>Code</td>
                <td><%= @item.code %></td>
              </tr>
              <tr>
                <td>Description</td>
                <td><%= @item.description %></td>
              </tr>
              <tr>
                <td>Quantity</td>
                <td><%= @item.quantity %></td>
              </tr>
              <tr>
                <td>Safety Stock</td>
                <td><%= @item.safetystock %></td>
              </tr>
              <tr>
                <td>Reorder Level</td>
                <td><%= @item.reorderlevel %></td>
              </tr>
              <tr>
                <td>Lead Time</td>
                <td><%= @item.leadtime %> days</td>
              </tr>
              <tr>
                <td>Created</td>
                <td><%= @item.created_at.in_time_zone("Chennai").strftime("%d/%m/%Y %I:%M %p") %></td>
              </tr>
              <tr>
                <td>Last Updated</td>
                <td><%= @item.updated_at.in_time_zone("Chennai").strftime("%d/%m/%Y %I:%M %p") %></td>
              </tr>
              <tr>
                <td>Delete</td>
                <td><%= link_to content_tag(:span, "", class: "glyphicon glyphicon-trash"), item_path(@item), :method => :delete, data: {confirm: "Are you sure?"} %></td>
              </tr>
            </tbody>
          </table>
          
          <div class="btn-group" role="group" aria-label="...">
            <%= link_to content_tag(:span, "", class: "glyphicon glyphicon-download-alt") + "Edit", edit_item_path(@item), class: "btn btn-default" %>
          </div>
          <br><br>
          <%= link_to content_tag(:span, "", class: "glyphicon glyphicon-arrow-left") + "Back", root_path %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("logo.png", class: "logo") + "Fracktal Works", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%=content_tag(:span, "", class: "glyphicon glyphicon-user") + current_user.name %> <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <%= content_tag(:li) do %>
                <%= link_to content_tag(:span, "", class: "glyphicon glyphicon-list") + "Dashboard", root_path %>
              <% end %>
              <li class="divider"></li>
              <%= content_tag(:li) do %>
                <%= link_to content_tag(:span, "", class: "glyphicon glyphicon-log-out") + "Logout", destroy_user_session_path, :method => :delete %>
              <% end %>
            </ul>
          </li>
        <% else %>
          <li><%= link_to content_tag(:span, "", class: "glyphicon glyphicon glyphicon-log-in") + "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-info">
    <button data-dismiss="alert" class="close">x</button>
      <ul>
        <li>
          <%= value %>
        </li>
      </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Frackint</title>
  <%= favicon_link_tag 'favicon.png' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
<div class="container">
  <%= render 'layouts/messages' %>
  <%= yield %>
</div>

</body>
</html>